export const row = [
	{
		date: '2017-06-01',
		id: 1,
		road_no: 'RN1',
		road_name: 'Road A',
		start_chainage: 10,
		end_chainage: 20,
		type: 'Type1',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2017-06-01',
		id: 2,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 20,
		end_chainage: 30,
		type: 'Type2',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2017-06-01',
		id: 3,
		road_no: 'RN3',
		road_name: 'Road C',
		start_chainage: 30,
		end_chainage: 40,
		type: 'Type3',
		condition: [10, 55, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2017-06-01',
		id: 4,
		road_no: 'RN4',
		road_name: 'Road D',
		start_chainage: 40,
		end_chainage: 50,
		type: 'Type4',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2017-06-01',
		id: 5,
		road_no: 'RN5',
		road_name: 'Road E',
		start_chainage: 50,
		end_chainage: 60,
		type: 'Type5',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2017-06-01',
		id: 6,
		road_no: 'RN6',
		road_name: 'Road F',
		start_chainage: 60,
		end_chainage: 70,
		type: 'Type6',
		condition: [70, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2018-06-22',
		id: 7,
		road_no: 'RN7',
		road_name: 'Road G',
		start_chainage: 70,
		end_chainage: 80,
		type: 'Type7',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2020-08-04',
		id: 8,
		road_no: 'RN8',
		road_name: 'Road H',
		start_chainage: 80,
		end_chainage: 90,
		type: 'Type8',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2017-09-20',
		id: 9,
		road_no: 'RN9',
		road_name: 'Road I',
		start_chainage: 90,
		end_chainage: 100,
		type: 'Type9',
		condition: [10, 20, 30],
		trip_approval: 'Comparison.png',
	},
	{
		date: '2019-07-11',
		id: 10,
		road_no: 'RN10',
		road_name: 'Road J',
		start_chainage: 100,
		end_chainage: 110,
		type: 'Type10',
		condition: [10, 20, 30],
		trip_approval: 'Comaprison.png',
	},
	{
		date: '2017-06-01',
		id: 11,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type1',
	},
	{
		date: '2017-06-01',
		id: 12,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type2',
	},
	{
		date: '2017-06-01',
		id: 13,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type3',
	},
	{
		date: '2017-06-01',
		id: 14,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type4',
	},
	{
		date: '2017-06-01',
		id: 15,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type5',
	},
	{
		date: '2017-06-01',
		id: 16,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type6',
	},
	{
		date: '2018-06-22',
		id: 17,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type7',
	},
	{
		date: '2020-08-04',
		id: 18,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type8',
	},
	{
		date: '2017-09-20',
		id: 19,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type9',
	},
	{
		date: '2019-07-11',
		id: 20,
		road_no: 'RN2',
		road_name: 'Road B',
		start_chainage: 15 / 500,
		end_chainage: 25 / 200,
		type: 'Type10',
	},
];

export const dropdowndata = [
  {
    id: 1,
    name: "Pune",
    circle: [
      {
        id: 11,
        name: "Kolhapur",
        division: [
          {
            id: 111,
            name: "North",
            subdivisions: [
              {
                id: 1111,
                name: "Nashik",
                roads: [
                  {
                    id: 11111,
                    name: "Road 1",
                    condition: [40, 50, 30],
                    road_no: "RN1",
                    road_name: "Road A",
                    start_chainage: 10,
                    end_chainage: 20,
                    type: "Type1",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 11112,
                    name: "Road 2",
                    condition: [70, 60, 20],
                    road_no: "RN2",
                    road_name: "Road B",
                    start_chainage: 20,
                    end_chainage: 30,
                    type: "Type2",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 1112,
                name: "Magarpatta",
                roads: [
                  {
                    id: 11121,
                    name: "Road A",
                    condition: [50, 30, 80],
                    road_no: "RN3",
                    road_name: "Road C",
                    start_chainage: 30,
                    end_chainage: 40,
                    type: "Type3",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 11122,
                    name: "Road B",
                    condition: [70, 90, 60],
                    road_no: "RN4",
                    road_name: "Road D",
                    start_chainage: 40,
                    end_chainage: 50,
                    type: "Type4",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
          {
            id: 112,
            name: "Sangali",
            subdivisions: [
              {
                id: 1121,
                name: "Shivajinagar",
                roads: [
                  {
                    id: 11211,
                    name: "Street X",
                    condition: [40, 50, 30],
                    road_no: "RN5",
                    road_name: "Road E",
                    start_chainage: 50,
                    end_chainage: 60,
                    type: "Type5",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 11212,
                    name: "Street Y",
                    condition: [70, 90, 60],
                    road_no: "RN6",
                    road_name: "Road F",
                    start_chainage: 60,
                    end_chainage: 70,
                    type: "Type6",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 1122,
                name: "Nighoj",
                roads: [
                  {
                    id: 11221,
                    name: "Street Z",
                    condition: [10, 90, 70],
                    road_no: "RN7",
                    road_name: "Road G",
                    start_chainage: 70,
                    end_chainage: 80,
                    type: "Type7",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 11222,
                    name: "Street W",
                    condition: [80, 30, 60],
                    road_no: "RN8",
                    road_name: "Road H",
                    start_chainage: 80,
                    end_chainage: 90,
                    type: "Type8",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 12,
        name: "Solapur",
        division: [
          {
            id: 121,
            name: "Shirol",
            subdivisions: [
              {
                id: 1211,
                name: "Odisha",
                roads: [
                  {
                    id: 12111,
                    name: "Highway 1",
                    condition: [80, 60, 20],
                    road_no: "RN9",
                    road_name: "Road I",
                    start_chainage: 90,
                    end_chainage: 100,
                    type: "Type9",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 12112,
                    name: "Highway 2",
                    condition: [30, 90, 70],
                    road_no: "RN10",
                    road_name: "Road J",
                    start_chainage: 100,
                    end_chainage: 110,
                    type: "Type10",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 1212,
                name: "Vardha",
                roads: [
                  {
                    id: 12121,
                    name: "Expressway A",
                    condition: [10, 80, 70],
                    road_no: "RN11",
                    road_name: "Road K",
                    start_chainage: 110,
                    end_chainage: 120,
                    type: "Type11",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 12122,
                    name: "Expressway B",
                    condition: [80, 60, 40],
                    road_no: "RN13",
                    road_name: "Road M",
                    start_chainage: 130,
                    end_chainage: 140,
                    type: "Type13",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
          {
            id: 122,
            name: "Shirur",
            subdivisions: [
              {
                id: 1221,
                name: "Bihar",
                roads: [
                  {
                    id: 12211,
                    name: "Main Road",
                    condition: [50, 20, 40],
                    road_no: "RN14",
                    road_name: "Road N",
                    start_chainage: 140,
                    end_chainage: 150,
                    type: "Type14",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 12212,
                    name: "Side Street",
                    condition: [40, 30, 70],
                    road_no: "RN15",
                    road_name: "Road O",
                    start_chainage: 150,
                    end_chainage: 160,
                    type: "Type15",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 1222,
                name: "Alibaug",
                roads: [
                  {
                    id: 12221,
                    name: "Coastal Road",
                    condition: [60, 40, 80],
                    road_no: "RN16",
                    road_name: "Road P",
                    start_chainage: 160,
                    end_chainage: 170,
                    type: "Type16",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 12222,
                    name: "Beach Drive",
                    condition: [30, 80, 10],
                    road_no: "RN17",
                    road_name: "Road Q",
                    start_chainage: 170,
                    end_chainage: 180,
                    type: "Type17",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Mumbai",
    circle: [
      {
        id: 21,
        name: "Dapoli",
        division: [
          {
            id: 211,
            name: "Shikrapur",
            subdivisions: [
              {
                id: 2111,
                name: "Hadapsar",
                roads: [
                  {
                    id: 21111,
                    name: "Main Street",
                    condition: [20, 50, 40],
                    road_no: "RN18",
                    road_name: "Road R",
                    start_chainage: 180,
                    end_chainage: 190,
                    type: "Type18",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 21112,
                    name: "Side Street",
                    condition: [10, 20, 30],
                    road_no: "RN19",
                    road_name: "Road S",
                    start_chainage: 190,
                    end_chainage: 200,
                    type: "Type19",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 2112,
                name: "Manchar",
                roads: [
                  {
                    id: 21121,
                    name: "Business Boulevard",
                    condition: [30, 80, 40],
                    road_no: "RN20",
                    road_name: "Road T",
                    start_chainage: 200,
                    end_chainage: 210,
                    type: "Type20",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 21122,
                    name: "Commerce Lane",
                    condition: [30, 40, 50],
                    road_no: "RN21",
                    road_name: "Road U",
                    start_chainage: 210,
                    end_chainage: 220,
                    type: "Type21",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
          {
            id: 212,
            name: "Wagholi",
            subdivisions: [
              {
                id: 2121,
                name: "Nagar",
                roads: [
                  {
                    id: 21211,
                    name: "Market Road",
                    condition: [40, 70, 10],
                    road_no: "RN22",
                    road_name: "Road V",
                    start_chainage: 220,
                    end_chainage: 230,
                    type: "Type22",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 21212,
                    name: "Shopping Street",
                    condition: [30, 80, 90],
                    road_no: "RN23",
                    road_name: "Road W",
                    start_chainage: 230,
                    end_chainage: 240,
                    type: "Type23",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 2122,
                name: "Goa",
                roads: [
                  {
                    id: 21221,
                    name: "Tourist Drive",
                    condition: [30, 40, 10],
                    road_no: "RN24",
                    road_name: "Road X",
                    start_chainage: 240,
                    end_chainage: 250,
                    type: "Type24",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 21222,
                    name: "Resort Lane",
                    condition: [60, 80, 90],
                    road_no: "RN25",
                    road_name: "Road Y",
                    start_chainage: 250,
                    end_chainage: 260,
                    type: "Type25",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 22,
        name: "Chinchwad",
        division: [
          {
            id: 221,
            name: "pcmc",
            subdivisions: [
              {
                id: 2211,
                name: "Haveli",
                roads: [
                  {
                    id: 22111,
                    name: "Technology Avenue",
                    condition: [80, 10, 30],
                    road_no: "RN26",
                    road_name: "Road Z",
                    start_chainage: 260,
                    end_chainage: 270,
                    type: "Type26",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 22112,
                    name: "Innovation Street",
                    condition: [40, 70, 20],
                    road_no: "RN27",
                    road_name: "Road AA",
                    start_chainage: 270,
                    end_chainage: 280,
                    type: "Type27",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 2212,
                name: "Bhosari",
                roads: [
                  {
                    id: 22121,
                    name: "Industrial Road",
                    condition: [80, 60, 20],
                    road_no: "RN28",
                    road_name: "Road AB",
                    start_chainage: 280,
                    end_chainage: 290,
                    type: "Type28",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 22122,
                    name: "Factory Lane",
                    condition: [70, 80, 50],
                    road_no: "RN29",
                    road_name: "Road AC",
                    start_chainage: 290,
                    end_chainage: 300,
                    type: "Type29",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
          {
            id: 222,
            name: "Bhumkar",
            subdivisions: [
              {
                id: 2221,
                name: "Manapa",
                roads: [
                  {
                    id: 22211,
                    name: "Rural Route",
                    condition: [40, 30, 60],
                    road_no: "RN30",
                    road_name: "Road AD",
                    start_chainage: 300,
                    end_chainage: 310,
                    type: "Type30",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 22212,
                    name: "Countryside Drive",
                    condition: [10, 20, 90],
                    road_no: "RN31",
                    road_name: "Road AE",
                    start_chainage: 310,
                    end_chainage: 320,
                    type: "Type31",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
              {
                id: 2222,
                name: "Hinjawadi",
                roads: [
                  {
                    id: 22221,
                    name: "Tech Park Street",
                    condition: [10, 70, 80],
                    road_no: "RN32",
                    road_name: "Road AF",
                    start_chainage: 320,
                    end_chainage: 330,
                    type: "Type32",
                    trip_approval: "Comparison.png",
                  },
                  {
                    id: 22222,
                    name: "Corporate Boulevard",
                    condition: [10, 20, 30],
                    road_no: "RN33",
                    road_name: "Road AG",
                    start_chainage: 330,
                    end_chainage: 340,
                    type: "Type33",
                    trip_approval: "Comparison.png",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
